package org.example.java21demo;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("Record 全生态化测试")
class RecordDemoTest {

    private final RecordDemoService service = new RecordDemoService();
    private final ObjectMapper objectMapper = new ObjectMapper().findAndRegisterModules();

    // ==================== Record 基础特性测试 ====================

    @Test
    @DisplayName("Record 自动生成规范构造器、访问器和 equals")
    void testRecordAutoGenerated() {
        RecordDemoService.ProductDTO p1 = new RecordDemoService.ProductDTO(
                1L, "MacBook", new BigDecimal("9999"), "电子");
        RecordDemoService.ProductDTO p2 = new RecordDemoService.ProductDTO(
                1L, "MacBook", new BigDecimal("9999"), "电子");

        assertEquals(1L, p1.id());
        assertEquals("MacBook", p1.name());
        assertEquals(new BigDecimal("9999"), p1.price());
        assertEquals(p1, p2, "相同值的 Record 应 equals");
        assertEquals(p1.hashCode(), p2.hashCode(), "相同值的 Record 应有相同 hashCode");
    }

    @Test
    @DisplayName("Record.toString() 输出所有组件")
    void testRecordToString() {
        var product = new RecordDemoService.ProductDTO(1L, "iPhone", new BigDecimal("8999"), "电子");
        String str = product.toString();

        assertTrue(str.contains("iPhone"));
        assertTrue(str.contains("8999"));
        assertTrue(str.contains("电子"));
    }

    // ==================== Compact Constructor 验证测试 ====================

    @Test
    @DisplayName("合法邮箱创建成功")
    void testValidEmail() {
        RecordDemoService.Email email = new RecordDemoService.Email("user@example.com");
        assertEquals("user@example.com", email.value());
    }

    @Test
    @DisplayName("非法邮箱在构造时抛出异常")
    void testInvalidEmailRejected() {
        assertThrows(IllegalArgumentException.class,
                () -> new RecordDemoService.Email("no-at-sign"));
        assertThrows(IllegalArgumentException.class,
                () -> new RecordDemoService.Email(null));
    }

    // ==================== 泛型 Record 测试 ====================

    @Test
    @DisplayName("泛型 Record 保留类型信息")
    void testGenericRecord() {
        List<RecordDemoService.ProductDTO> items = List.of(
                new RecordDemoService.ProductDTO(1L, "A", BigDecimal.ONE, "X"),
                new RecordDemoService.ProductDTO(2L, "B", BigDecimal.TEN, "Y")
        );
        RecordDemoService.PageResult<RecordDemoService.ProductDTO> page =
                new RecordDemoService.PageResult<>(items, 1, 10, 50);

        assertEquals(2, page.items().size());
        assertEquals(1, page.page());
        assertEquals(50, page.total());

        // 类型安全：page.items().get(0) 是 ProductDTO
        RecordDemoService.ProductDTO first = page.items().get(0);
        assertEquals("A", first.name());
    }

    // ==================== 嵌套 Record 测试 ====================

    @Test
    @DisplayName("嵌套 Record 可深层访问")
    void testNestedRecordAccess() {
        var customer = new RecordDemoService.Customer(
                1L, "张三",
                new RecordDemoService.Email("zhangsan@example.com"),
                new RecordDemoService.Address("北京", "长安街 100 号", "100000")
        );

        assertEquals("北京", customer.address().city());
        assertEquals("zhangsan@example.com", customer.email().value());
        assertEquals("长安街 100 号", customer.address().street());
    }

    // ==================== Record 序列化测试 ====================

    @Test
    @DisplayName("Record 可序列化为 JSON")
    void testRecordToJson() throws JsonProcessingException {
        var customer = new RecordDemoService.Customer(
                1L, "李四",
                new RecordDemoService.Email("lisi@example.com"),
                new RecordDemoService.Address("上海", "南京路 200 号", "200000")
        );

        String json = objectMapper.writeValueAsString(customer);
        assertTrue(json.contains("李四"));
        assertTrue(json.contains("lisi@example.com"));
        assertTrue(json.contains("南京路 200 号"));
    }

    @Test
    @DisplayName("Record JSON 往返序列化保持等价")
    void testRecordJsonRoundtrip() throws JsonProcessingException {
        var original = new RecordDemoService.Customer(
                2L, "王五",
                new RecordDemoService.Email("wangwu@example.com"),
                new RecordDemoService.Address("广州", "中山路 50 号", "510000")
        );

        String json = objectMapper.writeValueAsString(original);
        RecordDemoService.Customer deserialized = objectMapper.readValue(json, RecordDemoService.Customer.class);

        assertEquals(original, deserialized);
    }

    // ==================== Record 实现接口测试 ====================

    @Test
    @DisplayName("Record 可实现接口并多态使用")
    void testRecordImplementsInterface() {
        List<RecordDemoService.Identifiable> items = List.of(
                new RecordDemoService.TagDTO(1L, "Java"),
                new RecordDemoService.TagDTO(2L, "Spring")
        );

        List<Long> ids = items.stream().map(RecordDemoService.Identifiable::id).toList();
        assertEquals(List.of(1L, 2L), ids);
    }

    // ==================== 自定义方法 Record 测试 ====================

    @Test
    @DisplayName("Record 支持实例方法和静态方法")
    void testRecordWithMethods() {
        RecordDemoService.Money m1 = new RecordDemoService.Money(new BigDecimal("100"), "CNY");
        RecordDemoService.Money m2 = new RecordDemoService.Money(new BigDecimal("50"), "CNY");
        RecordDemoService.Money sum = m1.add(m2);

        assertEquals(new BigDecimal("150"), sum.amount());
        assertEquals("CNY", sum.currency());

        RecordDemoService.Money zero = RecordDemoService.Money.zero("USD");
        assertEquals(BigDecimal.ZERO, zero.amount());
        assertEquals("USD", zero.currency());
    }

    @Test
    @DisplayName("不同币种的 Money 相加应抛异常")
    void testMoneyDifferentCurrency() {
        RecordDemoService.Money cny = new RecordDemoService.Money(BigDecimal.TEN, "CNY");
        RecordDemoService.Money usd = new RecordDemoService.Money(BigDecimal.ONE, "USD");

        assertThrows(IllegalArgumentException.class, () -> cny.add(usd));
    }

    // ==================== Local Record 测试 ====================

    @Test
    @DisplayName("方法内 Local Record 可用于排序等场景")
    void testLocalRecord() {
        record PersonScore(String name, int score) implements Comparable<PersonScore> {
            @Override
            public int compareTo(PersonScore o) {
                return Integer.compare(o.score, this.score);
            }
        }

        var scores = List.of(
                new PersonScore("Alice", 90),
                new PersonScore("Bob", 85),
                new PersonScore("Charlie", 95)
        );

        var sorted = scores.stream().sorted().toList();
        assertEquals("Charlie", sorted.get(0).name());
        assertEquals(95, sorted.get(0).score());
        assertEquals("Bob", sorted.get(2).name());
    }

    // ==================== 服务方法测试 ====================

    @Test
    @DisplayName("recordAsDto 返回正确产品信息")
    void testServiceRecordAsDto() {
        Map<String, Object> result = service.recordAsDto();
        assertEquals("MacBook Pro", result.get("name"));
        assertTrue((boolean) result.get("equals"));
    }

    @Test
    @DisplayName("genericRecord 返回泛型 Record")
    void testServiceGenericRecord() {
        Map<String, Object> result = service.genericRecord();
        assertEquals(100L, result.get("total"));
    }

    @Test
    @DisplayName("validationInConstructor 正确拒绝非法邮箱")
    void testServiceValidation() {
        Map<String, Object> result = service.validationInConstructor();
        assertTrue(result.get("invalidEmailResult").toString().contains("验证失败"));
    }

    @Test
    @DisplayName("recordsInStreams 返回正确的分组统计")
    void testServiceRecordsInStreams() {
        Map<String, Object> result = service.recordsInStreams();
        assertNotNull(result.get("summaries"));
        assertTrue(result.get("topCategory").toString().contains("热销品类"));
    }

    @Test
    @DisplayName("serializationDemo 往返序列化成功")
    void testServiceSerialization() throws JsonProcessingException {
        Map<String, Object> result = service.serializationDemo();
        assertTrue((boolean) result.get("roundtripEquals"));
    }

    @Test
    @DisplayName("localRecordDemo 方法内 Record 排序正确")
    void testServiceLocalRecord() {
        Map<String, Object> result = service.localRecordDemo();
        List<?> ranked = (List<?>) result.get("ranked");
        assertEquals(3, ranked.size());
    }

    @Test
    @DisplayName("传统 POJO vs Record 深度对比")
    void testComparePojoVsRecord() {
        Map<String, Object> result = service.comparePojoVsRecord();

        assertTrue(result.containsKey("pojo"));
        assertTrue(result.containsKey("record"));
        assertTrue(result.containsKey("comparison"));

        Map<String, Object> pojo = (Map<String, Object>) result.get("pojo");
        assertTrue(pojo.get("linesOfCode").toString().contains("40"));

        Map<String, Object> rec = (Map<String, Object>) result.get("record");
        assertEquals("1 行", rec.get("linesOfCode"));
    }
}
